agents:
  - name: example
    setup_script: echo 'Set up example agent'
    command: echo 'Run example agent'
  - name: fluyt
    setup_script: |
      curl -sL https://bosun-public.s3.eu-central-1.amazonaws.com/fluyt-cli -o /usr/local/bin/fluyt;
      chmod +x /usr/local/bin/fluyt
    command: echo 'Run fluyt agent'

repositories:
  - name: todolist
    url: https://github.com/bosun-ai/todolist.git
    setup_script: |
      curl -sL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh;
      bash nodesource_setup.sh;
      apt install -y nodejs;
      cd /todolist;
      npm install
    coverage_tool_command: |
      cd /todolist;
      npm test -- --coverage --watchAll=false --bail=1 -u && cat coverage/lcov.info
  # - name: derrick
  #   url: https://github.com/bosun-ai/derrick.git
  #   setup_script: |
  #     apt-get install -y build-essential lld curl;
  #     curl https://sh.rustup.rs -sSf | bash -s -- -y;
  #     echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
  #   coverage_tool_command: cargo tarpaulin
