runs: 1
results_path: tmp/results
agents:
  - name: qodo-cover 
    version: "0.2.11"
  - name: kwaak
    version: "v0.1.6"
  # - name: fluyt
  #   version: "latest"

repositories:
  - name: todolist
 # - name: derrick
  - name: tokei
