[project]
name = "agent-test-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyaml>=24.9.0",
    "pycobertura>=3.3.2",
    "requests>=2.32.3",
]
